"""add id_driver

Revision ID: 12d6347f0a05
Revises: 9428acb91486
Create Date: 2026-06-11 22:47:25.005124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d6347f0a05'
down_revision: Union[str, Sequence[str], None] = '9428acb91486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos_sistema', sa.Column('id_driver', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos_sistema', 'id_driver')
    # ### end Alembic commands ###
