"""add id_drive

Revision ID: c32de736dab0
Revises: 12d6347f0a05
Create Date: 2026-06-12 10:23:25.710966

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c32de736dab0"
down_revision: str | Sequence[str] | None = "12d6347f0a05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documentos_sistema", sa.Column("id_drive", sa.String(), nullable=True))
    op.drop_column("documentos_sistema", "id_driver")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documentos_sistema",
        sa.Column("id_driver", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("documentos_sistema", "id_drive")
    # ### end Alembic commands ###
